function E = PreLoadText_Part2b(E)
E.text.part2Intro = sprintf([ ...
    'Part II - scanner version\n\n' ...
    'Press the right arrow key to continue.' ]);

E.text.part2Start = sprintf([ ...
    'Waiting for scanner trigger.\n\n' ...
    'Press the trigger key to begin.' ]);

E.text.part2BlockBreak = sprintf([ ...
    'You have completed block %%d of %%d.\n\n' ...
    'Please take a moment of rest.\n\n' ...
    'When you are ready, press the right arrow key to start the next block.' ]);

E.text.part2Final = sprintf([ ...
    'Congratulations!\n\n' ...
    'You have finished the last task of Part II.\n\n' ...
    'See you for Part III, which will be fairly short. Thank you for participating!' ]);
end
