function E = PreLoadText_Part2b(E)
language = normalizeLanguage(E.sbj.lang);

if strcmp(language, 'en')
    E.text.part2Intro = sprintf([ ...
        'Part II - Scanner\n\n' ...
        'Waiting for experimenter...' ]);

    E.text.part2Start = sprintf([ ...
        'Waiting for scanner.' ]);

    E.text.part2BlockBreak = sprintf([ ...
        'You have completed run %%d of %%d.\n\n' ...
        'Please take a moment of rest.\n\n' ...
        'When you are ready, press the space bar to start the next run.' ]);

    E.text.part2Final = sprintf([ ...
        'Congratulations!\n\n' ...
        'You have finished the last task of Part II.\n\n' ...
        'See you for Part III. Thank you for participating!' ]);
else
    E.text.part2Intro = sprintf([ ...
        'Parte II - versione scanner\n\n' ...
        'Premi la barra spaziatrice per continuare.' ]);

    E.text.part2Start = sprintf([ ...
        'In attesa dello scanner.' ]);

    E.text.part2BlockBreak = sprintf([ ...
        'Hai completato la run %%d di %%d.\n\n' ...
        'Fai una breve pausa.\n\n' ...
        'Quando sei pronto, premi la barra spaziatrice per iniziare la run successiva.' ]);

    E.text.part2Final = sprintf([ ...
        'Complimenti!\n\n' ...
        'Hai terminato l''ultimo compito della Parte II.\n\n' ...
        'Ci vediamo per la Parte III. Grazie per la partecipazione!' ]);
end
end

function language = normalizeLanguage(rawLanguage)
language = lower(strtrim(string(rawLanguage)));

if startsWith(language, "en")
    language = 'en';
elseif startsWith(language, "it")
    language = 'it';
else
    language = 'it';
end
end
